# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Contact
    url: contact
    weight: 60
  - name: More Platforms
    identifier: more-platforms
    url: '#'
    weight: 70
  - name: 知乎
    url: 'https://www.zhihu.com/people/58-18-2-26-61'
    weight: 71
    parent: more-platforms
  - name: Bilibili
    url: 'https://space.bilibili.com/3493095748405551?spm_id_from=333.337.search-card.all.click'
    weight: 72
    parent: more-platforms
  - name: Email
    url: '#'
    weight: 73
    parent: more-platforms
    params:
      copyText: 'pku.alignment@gmail.com'
  - name: 小红书
    url: '#'
    weight: 74
    parent: more-platforms
    params:
      copyText: '94133423595'
  - name: PAIR-Lab
    url: 'https://pair-lab.ai/'
    weight: 75
    parent: more-platforms
